const topicInput = document.querySelector("#topic");
const iterationsInput = document.querySelector("#iterations");
const iterationsValue = document.querySelector("#iterations-value");
const runButton = document.querySelector("#run-simulation");
const consoleOutput = document.querySelector("#console-output");
const statusPill = document.querySelector("#status-pill");
const reportViewer = document.querySelector("#report-viewer");
const downloadMdButton = document.querySelector("#download-md");
const downloadPdfButton = document.querySelector("#download-pdf");
const downloadDocxButton = document.querySelector("#download-docx");

const metricSources = document.querySelector("#metric-sources");
const metricSummaries = document.querySelector("#metric-summaries");
const metricSubtopics = document.querySelector("#metric-subtopics");

const sourceToggles = Array.from(document.querySelectorAll("[data-source]"));

const subtopicSeeds = [
  "ethics and regulation",
  "recent academic breakthroughs",
  "deployment barriers in low-resource settings",
  "diagnostic accuracy and trust",
  "market adoption trends",
  "privacy and governance",
  "drug discovery acceleration",
  "human-AI collaboration",
];

let isRunning = false;
let timerIds = [];
let latestReportMarkdown = "";
let latestTopic = "research_topic";

function setIterationsLabel() {
  iterationsValue.textContent = `${iterationsInput.value} loops`;
}

function appendLine(text, tone = "") {
  const line = document.createElement("div");
  line.className = `console-line ${tone}`.trim();
  line.textContent = text;
  consoleOutput.appendChild(line);
  consoleOutput.scrollTop = consoleOutput.scrollHeight;
}

function resetConsole() {
  timerIds.forEach((id) => clearTimeout(id));
  timerIds = [];
  consoleOutput.innerHTML = "";
  metricSources.textContent = "0";
  metricSummaries.textContent = "0";
  metricSubtopics.textContent = "0";
  latestReportMarkdown = "";
  reportViewer.textContent = "Run the simulator to generate a research report.";
  toggleExportButtons(false);
}

function getSelectedSources() {
  return sourceToggles.filter((toggle) => toggle.checked).map((toggle) => toggle.dataset.source);
}

function updateStatus(text) {
  statusPill.textContent = text;
}

function toggleExportButtons(enabled) {
  downloadMdButton.disabled = !enabled;
  downloadPdfButton.disabled = !enabled;
  downloadDocxButton.disabled = !enabled;
}

function safeFileName(topic) {
  return topic.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "") || "research_topic";
}

function buildReportMarkdown(topic, loops, sources, discovered, stats) {
  const now = new Date().toLocaleString();
  const uniqueSubtopics = Array.from(new Set(discovered));
  return [
    `# Research Report: ${topic}`,
    "",
    `Generated on: ${now}`,
    "",
    "## Overview",
    `- Topic: ${topic}`,
    `- Iterations completed: ${loops}`,
    `- Sources selected: ${sources.join(", ") || "None"}`,
    `- Sources scanned: ${stats.totalSources}`,
    `- Summaries created: ${stats.totalSummaries}`,
    `- Subtopics discovered: ${stats.totalSubtopics}`,
    "",
    "## Key Findings",
    `The autonomous loop explored **${topic}** across ${sources.length || 0} data source(s) and produced concise summaries from each iteration.`,
    "Recurring themes include practical adoption constraints, governance and ethics, and future impact projections.",
    "",
    "## Discovered Subtopics",
    ...(uniqueSubtopics.length > 0 ? uniqueSubtopics.map((item) => `- ${item}`) : ["- No subtopics discovered"]),
    "",
    "## Notes",
    "- This report is generated by the web simulator and reflects synthetic demo output.",
    "- Replace simulator outputs with real backend responses to produce production-grade reports.",
  ].join("\n");
}

function downloadTextFile(fileName, content, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

function exportMarkdown() {
  if (!latestReportMarkdown) return;
  downloadTextFile(`${latestTopic}.md`, latestReportMarkdown, "text/markdown;charset=utf-8");
}

function exportPdf() {
  if (!latestReportMarkdown) return;
  const jsPdfApi = window.jspdf;
  if (!jsPdfApi || !jsPdfApi.jsPDF) {
    appendLine("⚠️ PDF library unavailable. Please check internet connection for CDN assets.", "muted");
    return;
  }

  const { jsPDF } = jsPdfApi;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const lines = doc.splitTextToSize(latestReportMarkdown, pageWidth - margin * 2);
  let y = margin;

  doc.setFont("courier", "normal");
  doc.setFontSize(10);
  lines.forEach((line) => {
    if (y > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += 14;
  });
  doc.save(`${latestTopic}.pdf`);
}

async function exportDocx() {
  if (!latestReportMarkdown) return;
  if (!window.docx || !window.saveAs) {
    appendLine("⚠️ DOCX library unavailable. Please check internet connection for CDN assets.", "muted");
    return;
  }

  const { Document, Packer, Paragraph, TextRun } = window.docx;
  const paragraphs = latestReportMarkdown.split("\n").map((line) => {
    const isHeading = line.startsWith("# ");
    const content = line.replace(/^#\s+/, "");
    return new Paragraph({
      children: [new TextRun({ text: content || " ", bold: isHeading })],
      spacing: { after: 180 },
    });
  });

  const documentObj = new Document({
    sections: [{ properties: {}, children: paragraphs }],
  });

  const blob = await Packer.toBlob(documentObj);
  window.saveAs(blob, `${latestTopic}.docx`);
}

async function runSimulation() {
  if (isRunning) {
    return;
  }

  const topic = topicInput.value.trim() || "AI in Healthcare";
  const loops = Number(iterationsInput.value);
  const sources = getSelectedSources();
  latestTopic = safeFileName(topic);

  resetConsole();
  isRunning = true;
  runButton.disabled = true;
  updateStatus("Running");

  appendLine("╔══════════════════════════════════════════╗", "muted");
  appendLine("║     ENDLESS RESEARCH AGENT  v1.0        ║", "muted");
  appendLine("╚══════════════════════════════════════════╝", "muted");
  appendLine(`Topic received: ${topic}`, "accent");
  appendLine("Connecting to backend research engine...", "muted");

  try {
    const response = await fetch("http://localhost:8000/research", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        topic: topic,
        iterations: loops,
        sources: sources
      })
    });

    if (!response.ok) {
      throw new Error(`Backend error: ${response.statusText}`);
    }

    const data = await response.json();
    const results = data.results || [];
    
    let totalSources = 0;
    let totalSummaries = 0;
    let totalSubtopics = 0;
    const discovered = [];

    // Simulate the iterative discovery process
    for (let i = 0; i < Math.min(loops, results.length + 1); i++) {
      const iteration = i + 1;
      appendLine(`Iteration ${iteration}: Analyzing source intelligence...`, "accent");
      await new Promise(r => setTimeout(r, 600));

      if (results[i]) {
        const res = results[i];
        totalSources++;
        totalSummaries++;
        metricSources.textContent = String(totalSources);
        metricSummaries.textContent = String(totalSummaries);
        
        appendLine(`🔍 ${res.source} -> Found: "${res.title}"`, "");
        appendLine(`📄 Summary: ${res.summary.substring(0, 100)}...`, "muted");
        
        const subtopic = `${topic}: ${res.title.split(' ').slice(0, 3).join(' ')}`;
        discovered.push(subtopic);
        totalSubtopics++;
        metricSubtopics.textContent = String(totalSubtopics);
        appendLine(`📌 Discovered angle -> ${subtopic}`, "success");
      } else {
        appendLine("Exploring related sub-queries...", "muted");
      }
      
      await new Promise(r => setTimeout(r, 400));
    }

    latestReportMarkdown = buildRealReport(topic, loops, sources, results, discovered);
    reportViewer.textContent = latestReportMarkdown;
    toggleExportButtons(true);
    appendLine(`📄 Report assembled: output/${latestTopic}_2026.md`, "success");
    appendLine(`Summary: ${results.length} real sources analyzed, ${totalSubtopics} new subtopics.`, "muted");
    updateStatus("Complete");

  } catch (error) {
    appendLine(`❌ Error: ${error.message}`, "error");
    appendLine("Ensure the FastAPI backend is running on http://localhost:8000", "muted");
    updateStatus("Error");
  } finally {
    isRunning = false;
    runButton.disabled = false;
  }
}

function buildRealReport(topic, loops, sources, results, discovered) {
  const now = new Date().toLocaleString();
  let sections = [
    `# Research Report: ${topic}`,
    "",
    `Generated on: ${now}`,
    "",
    "## Overview",
    `- Topic: ${topic}`,
    `- Iterations attempted: ${loops}`,
    `- Real sources analyzed: ${results.length}`,
    `- Sources selected: ${sources.join(", ") || "None"}`,
    "",
    "## Detailed Findings",
    ""
  ];

  results.forEach((res, idx) => {
    sections.push(`### ${idx + 1}. ${res.title}`);
    sections.push(`**Source:** [${res.source}](${res.link})`);
    sections.push(`**Snippet:** ${res.snippet}`);
    sections.push(`**Key Summary:** ${res.summary}`);
    sections.push("");
  });

  sections.push("## Discovered Subtopics for Further Research");
  discovered.forEach(sub => sections.push(`- ${sub}`));
  
  sections.push("");
  sections.push("## System Notes");
  sections.push("- This report contains real-world data fetched via DuckDuckGo and scraped via BeautifulSoup.");
  sections.push("- Text summarization performed by extractive logic on the backend.");

  return sections.join("\n");
}


iterationsInput.addEventListener("input", setIterationsLabel);
runButton.addEventListener("click", runSimulation);
downloadMdButton.addEventListener("click", exportMarkdown);
downloadPdfButton.addEventListener("click", exportPdf);
downloadDocxButton.addEventListener("click", () => {
  exportDocx().catch(() => {
    appendLine("⚠️ Failed to generate DOCX export.", "muted");
  });
});

setIterationsLabel();
appendLine("Console ready. Launch the demo to simulate the autonomous research workflow.", "muted");
